export const portfolioSeed = {
  profile: {
    name: "Kaushal Mayani",
    roles: ["Full Stack Developer", "MERN Stack Developer", "AI Enthusiast", "Problem Solver"],
    tagline: "B.Tech Information Technology · Parul University",
    university: "Parul University",
    bio: "I build full-stack web apps with the MERN stack, explore AI/ML to solve real-world problems, and love turning ideas into clean, scalable code.",
    github: "https://github.com/kaushal58",
    linkedin: "https://linkedin.com/in/kaushal-mayani",
    email: "kaushalmayani3969@gmail.com",
    phone: "+91 83473 60379",
    location: "Visavadar, Junagadh, Gujarat",
    profileImage: "/assets/profile.jpg",
    available: true,
  },  
  about: {
    summary:
      "Motivated B.Tech Information Technology student with hands-on experience in full-stack web development using the MERN stack, RESTful APIs, and responsive UI design. Skilled in C/C++, JavaScript, backend integration, and database management, and familiar with AI/ML concepts, Generative AI tools, and prompt engineering.",
    objective:
      "To join a forward-thinking engineering team where I can contribute to meaningful products, grow as a software engineer, and build technology that solves real-world problems at scale.",
    strengths: ["Problem Solving", "Clean Code", "Debugging", "Fast Learner", "Teamwork"],
    interests: ["Open Source", "AI/ML", "Web Development", "Competitive Programming", "Tech Blogs"],
    timeline: [
      {
        year: "2021",
        title: "Higher Secondary (Science)",
        desc: "Completed HSC Science stream at Apollo International School, Visavadar.",
      },
      {
        year: "2023",
        title: "Started B.Tech IT",
        desc: "Joined Parul University, Vadodara for Bachelor of Technology in Information Technology.",
      },
      {
        year: "2024",
        title: "MERN Stack Journey",
        desc: "Started building full-stack apps with React, Node.js, Express & MongoDB.",
      },
      {
        year: "2025",
        title: "Real-World Projects",
        desc: "Built Car Rental Booking System & Smart Faculty & Timetable Planner.",
      },
      {
        year: "2026",
        title: "AI + Full-Stack",
        desc: "Building AI Crop Guardian — a precision-farming platform with ML models.",
      },
    ],
  },
  skillGroups: [
    {
      label: "Frontend",
      color: "from-blue-500 to-cyan-400",
      icon: "Layers",
      items: [
        { name: "React.js", level: 90 },
        { name: "HTML5", level: 95 },
        { name: "CSS3", level: 90 },
        { name: "JavaScript", level: 90 },
        { name: "TypeScript", level: 80 },
      ],
    },
    {
      label: "Backend & APIs",
      color: "from-purple-500 to-pink-500",
      icon: "Cpu",
      items: [
        { name: "Node.js", level: 85 },
        { name: "Express.js", level: 85 },
        { name: "REST APIs", level: 88 },
        { name: "JWT Auth", level: 82 },
      ],
    },
    {
      label: "Databases",
      color: "from-emerald-500 to-teal-500",
      icon: "Database",
      items: [
        { name: "MongoDB", level: 85 },
        { name: "SQL", level: 78 },
      ],
    },
    {
      label: "Programming",
      color: "from-amber-500 to-orange-500",
      icon: "Code2",
      items: [
        { name: "C / C++", level: 88 },
        { name: "Java", level: 78 },
        { name: "Python", level: 85 },
      ],
    },
    {
      label: "AI / ML",
      color: "from-indigo-500 to-violet-500",
      icon: "Brain",
      items: [
        { name: "TensorFlow", level: 75 },
        { name: "OpenCV", level: 72 },
        { name: "Generative AI", level: 80 },
        { name: "Prompt Engineering", level: 82 },
      ],
    },
    {
      label: "Tools & Platforms",
      color: "from-rose-500 to-fuchsia-500",
      icon: "Wrench",
      items: [
        { name: "Git & GitHub", level: 90 },
        { name: "Postman", level: 85 },
        { name: "Docker", level: 72 },
        { name: "VS Code", level: 95 },
      ],
    },
  ],
  projects: [
    {
      title: "AI Crop Guardian",
      desc: "Full-stack AI-powered precision farming platform for crop disease detection, pest monitoring, smart irrigation prediction, and weather-based crop risk analysis.",
      image: "/assets/proj-plant.jpg",
      tech: ["React.js", "Node.js", "Express", "FastAPI", "MongoDB", "TensorFlow", "OpenCV"],
      features: [
        "JWT auth & role-based access",
        "Real-time notifications via Socket.io",
        "Microservices with FastAPI AI services",
      ],
      github: "https://github.com/kaushal58",
      demo: "#",
    },
    {
      title: "Car Rental Booking System",
      desc: "End-to-end MERN car rental booking platform with car listings, bookings, filtering, and admin management.",
      image: "/assets/proj-ecom.jpg",
      tech: ["React.js", "Node.js", "Express.js", "MongoDB"],
      features: ["Secure user authentication", "Admin dashboard & booking status", "Clean, modular REST APIs"],
      github: "https://github.com/kaushal58",
      demo: "#",
    },
    {
      title: "Smart Faculty & Timetable Planner",
      desc: "Responsive web app for smart faculty allocation and automated timetable generation for academic institutions.",
      image: "/assets/proj-sms.jpg",
      tech: ["React.js", "Node.js", "Express.js", "MongoDB"],
      features: ["Automated timetable scheduling", "CRUD & authentication", "Optimized DB handling"],
      github: "https://github.com/kaushal58",
      demo: "#",
    },
  ],
  experience: [
    {
      type: "Coursework",
      title: "Data Structures & Algorithms",
      org: "Parul University",
      period: "2024 — 2025",
      desc: "In-depth study of arrays, trees, graphs, DP; 150+ problems solved on LeetCode.",
    },
    {
      type: "Coursework",
      title: "Web Development",
      org: "Parul University",
      period: "2024 — 2025",
      desc: "Built responsive frontend apps and REST APIs with the MERN stack.",
    },
    {
      type: "Coursework",
      title: "Database Management Systems",
      org: "Parul University",
      period: "2024",
      desc: "SQL, normalization, transactions, and hands-on projects with MongoDB & MySQL.",
    },
    {
      type: "Coursework",
      title: "Machine Learning Basics",
      org: "Parul University",
      period: "2025",
      desc: "Fundamentals of supervised & unsupervised learning; applied in AI Crop Guardian.",
    },
    {
      type: "Focus",
      title: "Object-Oriented Programming",
      org: "Self-Driven",
      period: "Ongoing",
      desc: "OOP in C++ and Java — inheritance, polymorphism, design principles.",
    },
  ],
  education: [
    {
      degree: "B.Tech Information Technology",
      college: "Parul University",
      university: "Vadodara, Gujarat",
      cgpa: "7.43 / 10",
      year: "2023 — Present",
    },
    {
      degree: "Higher Secondary (Science)",
      college: "Apollo International School",
      university: "Visavadar, Gujarat",
      cgpa: "HSC",
      year: "2021 — 2023",
    },
  ],
  certificates: [
    {
      title: "Web Designing Certification",
      org: "Parul University · Continuing Education",
      year: "Jan 2026",
    },
  ],
  achievements: [
    {
      icon: "Trophy",
      title: "150+ LeetCode Problems Solved",
      desc: "Strong foundation in algorithmic problem solving and competitive programming.",
    },
    {
      icon: "Award",
      title: "AI Crop Guardian Project",
      desc: "Built a full-stack AI precision farming platform with microservices architecture.",
    },
    {
      icon: "Star",
      title: "Web Designing Certified",
      desc: "Completed hands-on web dev certification with responsive projects & REST APIs.",
    },
    {
      icon: "Trophy",
      title: "3 Full-Stack MERN Projects",
      desc: "Shipped end-to-end apps with auth, dashboards, and clean modular APIs.",
    },
  ],
  techStack: [
    "React.js",
    "Node.js",
    "Express.js",
    "MongoDB",
    "SQL",
    "FastAPI",
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C",
    "C++",
    "TensorFlow",
    "OpenCV",
    "REST APIs",
    "JWT",
    "Git",
    "GitHub",
    "Postman",
    "Docker",
    "HTML5",
    "CSS3",
  ],
  githubUsername: "kaushal58",
};
